$ANSIBLE_VAULT;1.1;AES256
34643433353730333330343035636333383734613462316535343838663266306239333633313131
3362643563663737326431663436313032616162333262630a363631346233336530343331663131
61373539356136336661353438663935333766373961643966346238313838396137373031646364
3437616432363862390a356232653634363330353262353534623339666430353831666236306263
31616163333935613230613662326535343266363965663337333736386537616464383235643238
64306366653135363164663862373637626435333233386164393538663266643836666434326434
36666261383432623733663134346262373032393830343465316234656466393334313636626436
30363836623932366365346633663063623637303766383631396464656533303463313733666339
